libs =
import libs += threadable%lib{threadable} doctest%lib{doctest}

exe{threadable-tests}: {hxx ixx txx cxx}{queue.test.cxx doctest_include.hxx doctest_define_main.cxx} $libs
{
  test = true
  install = false
  test.arguments = --no-intro
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
