libs =
import libs += \
  libthreadable%lib{threadable} \
  doctest%lib{doctest}

exe{threadable-tests}: {hxx cxx}{doctest* ring_buffer.test.cxx} $libs
{
  test = true
  install = false
  test.arguments = --no-intro
}

cxx.poptions =+ "-I$out_root" "-I$src_root"

if($cxx.id == 'gcc')
{
  cxx.coptions += -Wno-interference-size
}
