libs =
import libs += \
  libthreadable%lib{threadable} \
  doctest%lib{doctest}

exe{threadable-tests}: {hxx ixx txx cxx}{**} $libs
{
  test = true
  install = false
  test.arguments = --no-intro
}

cxx.poptions =+ "-I$out_root" "-I$src_root"
